env_name: "Ant-v4"
action_limit_high: null
action_limit_low: null
gamma: 0.99  
max_buffer_size: 100000 
start_timesteps: 5000  
timesteps_per_epoch: 1  
batch_size: 4096  
hidden_size: 512
max_grad_norm: 10  
tau: 0.005  
policy_update_freq: 2  
alpha: 0.1  
iterations: 1000000
seed: 42
model_save_path: "./models"
model_load_path: "/media/aznaur/311BBF169A1AA3E4/mnt/git/rl/models/actor_1_4096_1715961598.514517" # necessary for evaluation