env_name: "HalfCheetah-v4"
gamma: 0.99
max_buffer_size: 100000
start_timesteps: 5000
timesteps_per_epoch: 1
batch_size: 4096
hidden_size: 512
max_grad_norm: 10
tau: 0.005
policy_update_freq: 2
alpha: 0.1
iterations: 1000000
seed: 42
model_save_path: "./models"
model_load_path: null # necessary path for evaluation
